### ISSUE TITLE
Was testing done before committing to Master?

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/conjur-openshift#1]
There are symlinks broken through out every script.  I've had to re-modify the whole thing to get it working in its current state.

Can we get someone to review this on a dev branch and PR?

I would but I have no idea what's going on in here other than that.

**Comment by infamousjoeg** [comment]
This is going to be given to customers as an example.

**Comment by kgilpin** [comment]
How is this different than openkube?

**Comment by infamousjoeg** [comment]
I closed this after realizing the utils.sh script is essentially a config file with functions. I’ve got a PR ready for minishift. 

Also, this is a Conjur cluster (1-master, 2-standbys, haproxy) deployed into OpenShift and orchestrated in scripts assuming Vagrant is used to setup OpenShift.   OpenKube appears to demonstrate authn-k8s.
